include:
  - board: promicro_nrf52840
    shield: keyball61_left
  - board: promicro_nrf52840
    shield: keyball61_right
    snippet: studio-rpc-usb-uart
  - board: promicro_nrf52840
    shield: settings_reset
