manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mochukeeb
      url-base: https://github.com/mochukeeb
    - name: nuts
      url-base: https://github.com/coopy-nuts
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: mochukeeb
      revision: main
    - name: zmk-keyball-duplex-kscan
      remote: nuts
      revision: main
  self:
    path: config
